trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'snehalpalve/nginx2'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: '$(tag)'
        
#Create Artifacts and make available for the 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifest'
        itemPattern: '**/*.yaml'
        downloadPath: '$(System.ArtifactsDirectory)'
      
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'Kubernetes-Service-Connection'
        namespace: 'default'
        manifests: '(System.ArtifactsDirectory)/Webserver-Apps/01-NginxApp1-Deployment.yml'
        containers: 'snehalpalve/nginx1:{tag}'